### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by amrrs** [lkwq007/stablediffusion-infinity#1]
Thanks for the great work and sharing it on Colab.

I hit PIL Resampling not found error.

```
import PIL.Image
if not hasattr(PIL.Image, 'Resampling'):  # Pillow<9.0
  PIL.Image.Resampling = PIL.Image
# Now PIL.Image.Resampling.BICUBIC is always recognized.

```

Adding this helped before the last line. Just leaving it here in case if anyone hits the same error.

**Comment by lkwq007** [comment]
Thanks for the suggestion. Seems that I forgot to restart runtime after upgrading PIL.
