### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [lkwq007/stablediffusion-infinity#10]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by lkwq007** [comment]
I'll add an open source license later. (Currently I am not sure to choose which one)

**Comment by TechnologyClassroom** [comment]
A practical first step is to find the licenses for all of the [dependencies](https://github.com/lkwq007/stablediffusion-infinity/blob/master/environment.yml).  The licenses of the dependencies often narrows down the choices.

**Comment by lkwq007** [comment]
Apache-2.0 license added.
