### ISSUE TITLE
[Question] What is the diff between the outpainting models?

### ISSUE THREAD

**Issue by bbecausereasonss** [lkwq007/stablediffusion-infinity#104]
Are they all 1.5?

What is the 1.5+IMG2IMG vs the out painting model? A little confusing, thanks!

**Comment by lkwq007** [comment]
Only the first two options use the inpainting model

`stablediffusion-inpainting`: https://huggingface.co/runwayml/stable-diffusion-inpainting
`stablediffusion-inpainting+img2img-v1.5`: a combination of https://huggingface.co/runwayml/stable-diffusion-inpainting + https://huggingface.co/runwayml/stable-diffusion-v1-5 

`stablediffusion-v1.5`: https://huggingface.co/runwayml/stable-diffusion-v1-5
`stablediffusion-v1.4`: https://huggingface.co/CompVis/stable-diffusion-v1-4
