### ISSUE TITLE
PNG with transparent pixels

### ISSUE THREAD

**Issue by lisandropuzzolo** [lkwq007/stablediffusion-infinity#11]
When I upload a PNG with transparent pixels, they are treated as black pixels. 
![descarga (7) (1)](https://user-images.githubusercontent.com/2000988/190474141-140ecaab-3316-4620-adbe-cd7a8a090210.png)
![image](https://user-images.githubusercontent.com/2000988/190474192-1d1e91f3-e153-4464-80d7-90e0ef04b2d6.png)

**Comment by lkwq007** [comment]
Fixed with https://github.com/lkwq007/stablediffusion-infinity/commit/7736d99460cf2dca7bdc0fedea9f2827164815a9
