### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ninjasaid2k** [lkwq007/stablediffusion-infinity#110]
**Is your feature request related to a problem? Please describe.**
I find that pressing outpaint every time for generating a picture does not feel nice/.

**Describe the solution you'd like**
A right click on the canvas and a drop down menu that says outpaint or inpaint like this
![image](https://user-images.githubusercontent.com/99513716/197444324-0d2a2c97-d727-41d6-8bf7-6d3eeea5aaa2.png

**Comment by lkwq007** [comment]
How about using the keyboard shortcut? 
https://github.com/lkwq007/stablediffusion-infinity/blob/master/docs/usage.md#keyboard-shortcut
