### ISSUE TITLE
[Bug] Infinity now ridiculously slow

### ISSUE THREAD

**Issue by Bill4321** [lkwq007/stablediffusion-infinity#123]
**Describe the bug**

Yesterday I was able to use the repo fine, each output took circa 20 seconds. Today I have had to reinstall from scratch and it now takes 15 seconds PER STEP. To produce one image is going to take 12-15 minutes therefore sadly infinity is now broken for me. I use the vanilla install, no Taichi or other fixes and install the diffusers through a huggingface token. 

**To Reproduce**

Delete the repo and environment then reinstall. As I have done many times before when things stopped working.

**Expected behavior**

It to work :D

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox

**Additional context**

Feeling brave I uninstalled Anaconda3 and deleted the .cache subfolder to see if that would help. It didn't. I then uninstalled/reinstalled Automatic1111's repo to see if that had changed but that's the same as always, one image using the PLMS scheduler, 50 steps at 512x512 takes about 10 seconds. So sadly I give up :-)

**Comment by supersonic13** [comment]
I thought it was just me. installed infinity for the first time and each image takes about 15-20 minutes to generate - so uninstalled it. But keep to follow if there're any updates !

**Comment by magaspah** [comment]
Same here.  Following

**Comment by Bill4321** [comment]
Ok, I think that I have sorted it! It looks as if Infinity was working off of the CPU rather GPU. Feel free to try the fix but obviously I guarantee nothing, nothing at all..!

Delete 'libiomp5md.dll' from within envs\sd-inf\Library\bin\

From anaconda avtivate the environment (conda activate sd-inf)

Then..

pip uninstall torch
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

Now just run app.py as normal. The first time it ran it downloaded a couple of gigs of files again but after that everything is running smoothly.

**Comment by cryptobits** [comment]
I had this issue in Windows 10 as well. The pytorch channel does not have a latest (1.13.0) for python 3.10 and cuda 11.3. I was able to install a cuda version by setting the version "conda install pytorch=1.12.1 -c pytorch".

**Comment by tanglangxia** [comment]
I also have this problem and did what you said, but at the moment Infinity still works on the CPU and the GPU doesn't work at all, is there any other solution?

**Comment by somenewaccountthen** [comment]
yeah tip of the day: Yeah whenever it super slow check GPU/CPU is used. 
Also sometimes i see a message about CPU enhanced instruction support and i know i am up a creek without my GPU-paddle. 


@tanglangxia I just redo the repo, if it still fails i usually come to the repo ISSUEs and check for similar errors.
I usually end up pip/conda uninstall pytorch and google how to install pytorch with GPU support.
This repo been rock solid for me mostly though. Knock on wood. :P (Linux though. Is all just easier to get repos working i find,)

**Comment by tanglangxia** [comment]
I followed the command:
           conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch 
when installing, I found that the version directly given are cpu version, very strange

  pytorch pytorch/win-64::pytorch-1.13.0-py3.10_cpu_0
  pytorch-mutex pytorch/noarch::pytorch-mutex-1.0-cpu

  torchaudio pytorch/win-64::torchaudio-0.13.0-py310_cpu
  torchvision pytorch/win-64::torchvision-0.14.0-py310_cpu

**Comment by cryptobits** [comment]
I did **uninstall** pytorch first and I installed the cudatookit separately before installing pytorch. FWIW, I installed cudatoolkit=11.6 from the conda-forge channel instead of 11.3 from pytorch, but I doubt that part makes a big difference. I always got 1.13.0 cpu version until I specified pytorch=1.12.1.

**Comment by tanglangxia** [comment]
Sure enough it was the cudatoolkit version, this time I used the following command：

                   conda install pytorch=1.12.1 torchvision torchaudio cudatoolkit=11.6 -c pytorch

I successfully installed the cuda version of pytorch, thanks guys!

**Comment by abulka** [comment]
I tried the above command but it failed

```
conda install pytorch=1.12.1 torchvision torchaudio cudatoolkit=11.6 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.6

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by Bill4321** [comment]
Closing as Windows install instrutions have been updated.
