### ISSUE TITLE
fatal: destination path 'stablediffusion-infinity' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by RageshAntony** [lkwq007/stablediffusion-infinity#14]
I tried to run the colab. In the first time I got "Session crashed" error. 

<img width="933" alt="image" src="https://user-images.githubusercontent.com/36100215/190564187-6067a226-5cd9-4e22-8af4-172cde60f694.png">

After restarting I got..

fatal: destination path 'stablediffusion-infinity' already exists and is not an empty directory.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/36100215/190563881-a0bd6eb1-aa8f-4de9-bc3a-243a75699534.png">

How to fix this? Please help

**Comment by lkwq007** [comment]
the runtime is restarted via a runtime crash, so there is no need to restart the runtime or rerun the `setup libs` cell
