### ISSUE TITLE
[Feature Request] PNDM pull request?

### ISSUE THREAD

**Issue by mspiegel** [lkwq007/stablediffusion-infinity#165]
Any interest in a pull request that adds suport for the PNDM scheduler? It is the default scheduler in "NOP's Stable Diffusion" notebook. I don't pretend to understand the math or have any training as an artist, but PNDM seems to generate 'better' results in my art, for some subjective definition of better. I have created a fork that adds the scheduler. I wanted to see if there was any interest before I opened a pull request.

**Comment by lkwq007** [comment]
Pull requests are welcome!
