### ISSUE TITLE
[Bug] CoLab notebook fails to run

### ISSUE THREAD

**Issue by hartmutobendorf** [lkwq007/stablediffusion-infinity#170]
**Describe the bug**
When running the colab workbook, app.py fails, probably due to an error in PyPatchMatch

**To Reproduce**
1. Go to ['...'](https://colab.research.google.com/github/lkwq007/stablediffusion-infinity/blob/master/stablediffusion_infinity_colab.ipynb
2. Click on 'Runtime->Run all'
3. Scroll down to 'last cell'

**Expected behavior**

**Screenshots**
/content/stablediffusion-infinity
Compiling and loading c extensions from "/content/stablediffusion-infinity/PyPatchMatch".
rm -rf build/obj libpatchmatch.so
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
mkdir: created directory 'build/obj'
mkdir: created directory 'build/obj/csrc/'
[dep] csrc/nnf.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/inpaint.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/masked_image.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/pyinterface.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[CC] csrc/pyinterface.cpp ...
In file included from csrc/pyinterface.cpp:1:
csrc/pyinterface.h:1:10: fatal error: opencv2/core.hpp: No such file or directory
    1 | #include <opencv2/core.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:33: build/obj/csrc/pyinterface.o] Error 1

**Comment by hartmutobendorf** [comment]
It is. However, this seems to be the same error as in #163 
The same patch also works for me – changing opencv into opencv4
https://github.com/lkwq007/PyPatchMatch/compare/master...hartmutobendorf:PyPatchMatch:master

**Comment by lkwq007** [comment]
> It is. However, this seems to be the same error as in #163 The same patch also works for me – changing opencv into opencv4 [lkwq007/PyPatchMatch@master...hartmutobendorf:PyPatchMatch:master](https://github.com/lkwq007/PyPatchMatch/compare/master...hartmutobendorf:PyPatchMatch:master)

I have added a makefile fallback for `opencv4`. It should work now.

**Comment by grebenshyo** [comment]
have been trying it now , same error

**Comment by lkwq007** [comment]
@OMNISCIENTRAFI 

> [app.py can't find opencv in order to compile libpatchmatch.so]

If the program cannot find `opencv`, it will compile with `opencv4`. Perhaps I should modify `Makefile` directly but not use a fallback option to avoid confusion. 

> double free or corruption (out)

I can reproduce this bug. 
The error is actually related to photometric correction. (https://github.com/lkwq007/stablediffusion-infinity/blob/master/process.py)

**Comment by lkwq007** [comment]
@OMNISCIENTRAFI 

Fixed with the latest commit.

**Comment by OMNISCIENTRAFI** [comment]
yep, can confirm that the issue is fixed, although that issue of `Package opencv was not found in the pkg-config search path.` and `Perhaps you should add the directory containing "opencv.pc"` still persist, although with @sbersier #163  solution did fixed it

full cell output before the `/content/stablediffusion-infinity/PyPatchMatch/makefile` modification
```
Compiling and loading c extensions from "/content/stablediffusion-infinity/PyPatchMatch".
rm -rf build/obj libpatchmatch.so
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
mkdir: created directory 'build/obj'
mkdir: created directory 'build/obj/csrc/'
[dep] csrc/masked_image.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/pyinterface.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/nnf.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[dep] csrc/inpaint.cpp ...
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[CC] csrc/inpaint.cpp ...
csrc/inpaint.cpp:3:10: fatal error: opencv2/imgcodecs.hpp: No such file or directory
    3 | #include <opencv2/imgcodecs.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:33: build/obj/csrc/inpaint.o] Error 1
rm -rf build/obj libpatchmatch.so
mkdir: created directory 'build/obj'
mkdir: created directory 'build/obj/csrc/'
[dep] csrc/masked_image.cpp ...
[dep] csrc/pyinterface.cpp ...
[dep] csrc/nnf.cpp ...
[dep] csrc/inpaint.cpp ...
[CC] csrc/inpaint.cpp ...
[CC] csrc/nnf.cpp ...
[CC] csrc/pyinterface.cpp ...
[CC] csrc/masked_image.cpp ...
[link] libpatchmatch.so ...
---------------------------------------------------------
Found 1 CUDA devices
Device 0: Tesla T4
   SMs:        40
   Global mem: 15110 MB
   CUDA Cap:   7.5
---------------------------------------------------------
[PIE]Successfully initialize PIE grid solver with cuda backend

...and then public gradio link goes here
```

upon editing the makefile in `/content/stablediffusion-infinity/PyPatchMatch/makefile` with the sbersier solution
```
.....
CXXFLAGS += $(shell pkg-config --cflags opencv4) -fPIC
CXXFLAGS += $(INCLUDE_DIR)
LDFLAGS = $(shell pkg-config --cflags --libs opencv4) -shared -fPIC
.....
```

full cell output with sbersier solution
```
Compiling and loading c extensions from "/content/stablediffusion-infinity/PyPatchMatch".
rm -rf build/obj libpatchmatch.so
mkdir: created directory 'build/obj'
mkdir: created directory 'build/obj/csrc/'
[dep] csrc/masked_image.cpp ...
[dep] csrc/pyinterface.cpp ...
[dep] csrc/nnf.cpp ...
[dep] csrc/inpaint.cpp ...
[CC] csrc/inpaint.cpp ...
[CC] csrc/nnf.cpp ...
[CC] csrc/pyinterface.cpp ...
[CC] csrc/masked_image.cpp ...
[link] libpatchmatch.so ...
---------------------------------------------------------
Found 1 CUDA devices
Device 0: Tesla T4
   SMs:        40
   Global mem: 15110 MB
   CUDA Cap:   7.5
---------------------------------------------------------
[PIE]Successfully initialize PIE grid solver with cuda backend

...and then public gradio link goes here
```

**Comment by lkwq007** [comment]
> yep, can confirm that the issue is fixed, although that issue of `Package opencv was not found in the pkg-config search path.` and `Perhaps you should add the directory containing "opencv.pc"` still persist, although with @sbersier #163 solution did fixed it
> 
> full cell output before the `/content/stablediffusion-infinity/PyPatchMatch/makefile` modification
> 
> ```
> Compiling and loading c extensions from "/content/stablediffusion-infinity/PyPatchMatch".
> rm -rf build/obj libpatchmatch.so
> Package opencv was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opencv.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opencv' found
> mkdir: created directory 'build/obj'
> mkdir: created directory 'build/obj/csrc/'
> [dep] csrc/masked_image.cpp ...
> Package opencv was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opencv.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opencv' found
> [dep] csrc/pyinterface.cpp ...
> Package opencv was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opencv.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opencv' found
> [dep] csrc/nnf.cpp ...
> Package opencv was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opencv.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opencv' found
> [dep] csrc/inpaint.cpp ...
> Package opencv was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opencv.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opencv' found
> [CC] csrc/inpaint.cpp ...
> csrc/inpaint.cpp:3:10: fatal error: opencv2/imgcodecs.hpp: No such file or directory
>     3 | #include <opencv2/imgcodecs.hpp>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:33: build/obj/csrc/inpaint.o] Error 1
> rm -rf build/obj libpatchmatch.so
> mkdir: created directory 'build/obj'
> mkdir: created directory 'build/obj/csrc/'
> [dep] csrc/masked_image.cpp ...
> [dep] csrc/pyinterface.cpp ...
> [dep] csrc/nnf.cpp ...
> [dep] csrc/inpaint.cpp ...
> [CC] csrc/inpaint.cpp ...
> [CC] csrc/nnf.cpp ...
> [CC] csrc/pyinterface.cpp ...
> [CC] csrc/masked_image.cpp ...
> [link] libpatchmatch.so ...
> ---------------------------------------------------------
> Found 1 CUDA devices
> Device 0: Tesla T4
>    SMs:        40
>    Global mem: 15110 MB
>    CUDA Cap:   7.5
> ---------------------------------------------------------
> [PIE]Successfully initialize PIE grid solver with cuda backend
> 
> ...and then public gradio link goes here
> ```
> 

With the makefile fallback, `libpatchmatch.so` will be compiled twice: 
- compile with `opencv`
- if compiling with `opencv` fails, compile with `opencv4`

**Comment by lkwq007** [comment]
The colab notebook now should work well. So I'll close this issue.
