### ISSUE TITLE
[Bug]stablediffusion-infinity download things, but where + It broke my 1111

### ISSUE THREAD

**Issue by ksorah1** [lkwq007/stablediffusion-infinity#174]
Hello,

stablediffusion-infinity folder is 1.20mo and the stablediffusion one does not move. In addition to that, these AIs are all installed on c:/ which is by nature limited in storage and that they are SSDs, and therefore fragile to data movements, so I don't want it to download the thing x3 for each UI

![2023-01-22_191107](https://user-images.githubusercontent.com/112913359/213932756-75836d51-59ba-43c3-aead-10a25d35da89.jpg)

**Comment by ksorah1** [comment]
that's crazy dude, I already have SD1.4 model. 

![Uploading 2023-01-22_192722.jpg…]()

**Comment by lkwq007** [comment]
It seems that the program is not using the GPU. Please check if you have installed the pytorch cuda version correctly.

**Comment by ksorah1** [comment]
Where are located the files ?

**Comment by lkwq007** [comment]
> Where are located the files ?

`USER_DIRECTORY/.cache/huggingface/diffusers`
https://github.com/huggingface/diffusers/blob/main/src/diffusers/utils/constants.py#L20
