### ISSUE TITLE
[Bug]UserWarning: Failed to load image Python extension

### ISSUE THREAD

**Issue by ksorah1** [lkwq007/stablediffusion-infinity#175]
**Describe the bug**
When I run my UI, I have an error in addition.

[PIE]Successfully initialize PIE grid solver with taichi-cpu backend
C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\x\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
Running on local URL:  http://127.0.0.1:7861

**To Reproduce**
I just run the UI

**Desktop (please complete the following information):**
 - w10
 -chrome

**Comment by lkwq007** [comment]
All your issues (https://github.com/lkwq007/stablediffusion-infinity/issues/175, https://github.com/lkwq007/stablediffusion-infinity/issues/174, https://github.com/lkwq007/stablediffusion-infinity/issues/173) seems to be related to your python environment setup. 

You might need to create a virtual environment separately to run the program. In that case, installing all these packages will not break your default python installation.
