### ISSUE TITLE
[Feature Request] Regular python support (instead of conda)

### ISSUE THREAD

**Issue by Yasand123** [lkwq007/stablediffusion-infinity#178]
I tried using python/pip to install the dependencies, most of them installed fine but a couple failed (I get `ModuleNotFoundError: No module named 'diffusers'`). I'm assuming they're conda packages? I personally prefer using pip/python directly especially with the fact that I'm on Arch linux, it's not recommended to use conda/anaconda as it messes with permissions. It's kind of a pain to get conda running properly.

**Comment by lkwq007** [comment]
> I'm assuming they're conda packages?

`diffusers` also exists on PyPI: https://pypi.org/project/diffusers/

```
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
pip install scipy scikit-image
pip install diffusers==0.11.1 transformers ftfy accelerate
pip install opencv-python
pip install -U gradio
pip install pytorch-lightning==1.7.7 einops==0.4.1 omegaconf==2.2.3
pip install timm
```

**Comment by Yasand123** [comment]
Thank you. That worked.
