### ISSUE TITLE
[Questions] How can I run the code locally to batch-process images？

### ISSUE THREAD

**Issue by MqLeet** [lkwq007/stablediffusion-infinity#195]
Hi! I am new in this field, and I want to implement an outpainting operation on my own dataset.
When I clone the code to my machine, I found that when I run app.py, a local website was running, thus I cannot process my dataset in batch. Is there any solutions to run the code locally to process images in batch?

**Comment by 1ssb** [comment]
What is the answer to this?

**Comment by MqLeet** [comment]
> What is the answer to this?

Hi @1ssb , please refer to the python scripts written by me at https://github.com/MqLeet/outpainting-sd-inf/blob/main/Inference_local.py

**Comment by 1ssb** [comment]
Thank you for the response. This is exactly what I am using currently but there was intermediate XL model in the diffusers library that gave the same results as the runway model. I was interested in the stable diffusion XL pipeline though. Currently turbo does the similar sort of thing, but it’s not photorealistic enough.

Best Regards,

Subhransu
________________________________
