### ISSUE TITLE
Smaller environment.yml?

### ISSUE THREAD

**Issue by darthdeus** [lkwq007/stablediffusion-infinity#2]
Looks like the `environment.yml` might've been generated by freezing a global system environment, since it includes a ton of things including stuff like `alsa-lib` and a bunch of X11 stuff.

Could we get only the actual deps of the script? I tried to go through it manually but there's too many to try it one by one.

**Comment by lkwq007** [comment]
I'll list necessary deps and add a smaller one later.

**Comment by lkwq007** [comment]
Smaller environment.yml added.

**Comment by urbanscribe** [comment]
Thanks.  was still unable to build the full env.
getting stuck with the appended =pyhd8ed1ab_1 (example) specifications
tried to lookup channels that may have the packages

HOWEVER the step by step POST ENV CREATE conda install sequence you added to README works in Windows
