### ISSUE TITLE
inpaint is not defined

### ISSUE THREAD

**Issue by mrvirus9898** [lkwq007/stablediffusion-infinity#20]
Hello, attempting to use this software in a local environment. Installed per the readme without issues. Launched into the JupyterLab Notebook. Ran all the cells until the end when the GUI appeared. Uploaded a picture, moved the frame outside the image and clicked "Outpainting" and the following error was thrown.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [6], line 22, in run_outpaint(btn)
     20     # mask_image=mask_image.filter(ImageFilter.GaussianBlur(radius = 8))
     21     with autocast("cuda"):
---> 22         images = inpaint(
     23             prompt=base.text_input.value,
     24             init_image=init_image.resize(
     25                 (process_size, process_size), resample=Image.Resampling.LANCZOS
     26             ),
     27             mask_image=mask_image.resize((process_size, process_size)),
     28             strength=strength_slider.value,
     29             num_inference_steps=step_input.value,
     30             guidance_scale=guidance_input.value,
     31         )["sample"]
     32 else:
     33     with autocast("cuda"):

NameError: name 'inpaint' is not defined

**Comment by mrvirus9898** [comment]
Windows 10
Conda
JupyterLab Notebook

**Comment by lkwq007** [comment]
Please check the output of "setup StableDiffusionInpaintPipeline"
