### ISSUE TITLE
Laggy canvas fix ?

### ISSUE THREAD

**Issue by tzhf** [lkwq007/stablediffusion-infinity#21]
I wonder why the canvas is so laggy. It's so laggy i just gave up.

This process is ultra simple and shouldn't rely on any GPU. 
There's no strong calculations here, it's just moving an image on a canvas, any browser handle this.

This process shouldn't be handled by the server, only the browser client.
Pretty sure there's a workaround by letting the browser handling the canvas process, then transmitting the current position of the image/selected area to SD when needed.

**Comment by ayzick** [comment]
I'm having the same issue

**Comment by lkwq007** [comment]
Moving all interactions to the front end can fix this issue, and it requires rewriting the whole code base (e.g. a js front end for canvas interactions and a python server for handling inpainting requests). Currently, I have been busy with my research projects, so I might not be able to implement that.

**Comment by lkwq007** [comment]
I have ported the canvas interaction to frontend via pyscript. Now the colab version should work fine.
