### ISSUE TITLE
Package opencv was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by Baquara** [lkwq007/stablediffusion-infinity#24]
When running:

`jupyter lab`

Then going to:

`http://localhost:8888/lab`

Then finally:

`stablediffusion_infinity.ipynb`

The following happens on the "import libs" step:

```
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv', required by 'virtual:world', not found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv', required by 'virtual:world', not found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv', required by 'virtual:world', not found

```
![error](https://user-images.githubusercontent.com/9168959/192128610-986f93bd-23c1-4f9e-9138-46ffef25789e.png)

It is a fresh install and might be reproducible under a similar (Arch Linux) environment.

**Comment by lkwq007** [comment]
Have you installed the `opencv` library?
If installed, perhaps you need to modify the `Makefile`: changing `opencv` to `opencv4`
