### ISSUE TITLE
Canvas not showing up

### ISSUE THREAD

**Issue by borjan2** [lkwq007/stablediffusion-infinity#28]
Using google notebook. Everything works fine and can export images, but I don't have a canvas and can't actually see them. Can't move around the box and can't see what images I upload. It worked the first time I tried to use it although I think I didn't run every piece of code when I did that so the prompts wouldn't work.

**Comment by lkwq007** [comment]
Seems that colab changes the layout of hidden code cell and these two lines are not executed after the runtime crash:
```
from google.colab import output
output.enable_custom_widget_manager()
```
I just updated the colab and fixed this issue

**Comment by lkwq007** [comment]
I'll close this issue as `ipycanvas` is not longer used in the latest version.
