### ISSUE TITLE
Colab is missing libraries

### ISSUE THREAD

**Issue by krummrey** [lkwq007/stablediffusion-infinity#3]
Utils and canvas are missing when I try to run the notebook. Tried to in stall with` !pip install utils canvas`
it still fails, probably the wron canvas library?

```
ImportError                               Traceback (most recent call last)
[<ipython-input-4-a4748a0d1586>](https://localhost:8080/#) in <module>
      8 
      9 from utils import *
---> 10 from canvas import InfCanvas
     11 
     12 import numpy as np

ImportError: cannot import name 'InfCanvas' from 'canvas' (/usr/local/lib/python3.7/dist-packages/canvas/__init__.py)
```

**Comment by LEBMD** [comment]
Facing the same issue

**Comment by fidofetch** [comment]
Removing this line fixed the issue for me.

**Comment by LEBMD** [comment]
It should be working now

**Comment by lkwq007** [comment]
Fixed via PR https://github.com/lkwq007/stablediffusion-infinity/pull/6

**Comment by orangpelupa** [comment]
> Removing this line fixed the issue for me.

removing what line and where?
