### ISSUE TITLE
Setup failed - Invalid token!

### ISSUE THREAD

**Issue by nerdyrodent** [lkwq007/stablediffusion-infinity#30]
Using either a read or write token, during setup it always states "Invalid token!"?

**Comment by lkwq007** [comment]
You may need to enable your access to the model weights first: https://huggingface.co/CompVis/stable-diffusion-v1-4

**Comment by nerdyrodent** [comment]
Still no go. I run ```huggingface-cli login``` first and it says all is good and it saved my token. I then run the app and use the same  token. It fetches 16 items but then the error in the GUI appears?

**Comment by lkwq007** [comment]
> Still no go. I run `huggingface-cli login` first and it says all is good and it saved my token. I then run the app and use the same token. It fetches 16 items but then the error in the GUI appears?

Please check the error message reported by `python app.py` after clicking the setup.

**Comment by seekme-ai** [comment]
try accept authority, visit https://huggingface.co/CompVis/stable-diffusion-v1-4

**Comment by nerdyrodent** [comment]
app.py gives this output:

```
python app.py --port 7861
Compiling and loading c extensions from "/home/nerdy/github/stablediffusion-infinity/PyPatchMatch".
rm -rf build/obj libpatchmatch.so
mkdir: created directory 'build/obj'
mkdir: created directory 'build/obj/csrc/'
[dep] csrc/pyinterface.cpp ...
[dep] csrc/masked_image.cpp ...
[dep] csrc/inpaint.cpp ...
[dep] csrc/nnf.cpp ...
[CC] csrc/nnf.cpp ...
[CC] csrc/inpaint.cpp ...
[CC] csrc/masked_image.cpp ...
[CC] csrc/pyinterface.cpp ...
[link] libpatchmatch.so ...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 12478.41it/s]
```
