### ISSUE TITLE
Where to put previously downloaded Stable Diffusion model?

### ISSUE THREAD

**Issue by jasonmhead** [lkwq007/stablediffusion-infinity#34]
Where should someone put a previously downloaded Stable Diffusion model, and what should the model file be named?

Looking at def get_model() it's not immediately obvious where it would get put.

If any code modifications are needed to bypass the need for accessing HuggingFace (where the model has previously been downloaded from HuggingFace), what would be the recommendation?

**Comment by jasonmhead** [comment]
Getting the error, 

Error no file named model_index.json found in directory [my local model directory].

How would I find or create model_index.json

**Comment by lkwq007** [comment]
Check out 
https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/fp16 for `fp16` version
https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main for `fp32` version

**Comment by jasonmhead** [comment]
Thanks much!
I'm closer to a local install :)

I'll try and debug my current error: "Expecting value: line 1 column 1 (char 0)"

![local_install_infinity_diffusion](https://user-images.githubusercontent.com/6140151/193602804-5bf959e4-bd84-460a-ba90-7066ebf03422.JPG)

**Comment by toonpeters** [comment]
already any updates on how to implement a downloaded model?

**Comment by lkwq007** [comment]
> already any updates on how to implement a downloaded model?

https://github.com/lkwq007/stablediffusion-infinity/discussions/57

**Comment by lkwq007** [comment]
https://github.com/lkwq007/stablediffusion-infinity/blob/master/docs/usage.md

Loading a local model is supported in the latest version. 

```
python app.py --local_model path_to_model
```
