### ISSUE TITLE
Request: Keyboard shortcuts

### ISSUE THREAD

**Issue by AI-Guru** [lkwq007/stablediffusion-infinity#37]
Hi! What a fine tool you have created!

What about the following idea? In order to use the tool more efficient, it could make sense to introduce keyboard shortcuts to access the most important functionalities.

Keep up the great work!

-Tristan

**Comment by lkwq007** [comment]
Sounds a great idea. 
Do you have a suggestion on related key bindings?

**Comment by AI-Guru** [comment]
Great @lkwq007! Thanks!

I kinda kept track of what I am doing the most. There is a suggestion:

Key - Functionality
1 - Control: move selection
2 - Control: move canvas
3 - Control: brush

d - Outpaint (diffuse)
r - retry
c - commit
Cmd+Z - undo

What do you think?

Keep up the great work! I guess, I will  make a video later!

**Comment by lkwq007** [comment]
@AI-Guru 
Keyboard shortcut support is added. Can be configured via `config.yaml`.

**Comment by AI-Guru** [comment]
Awesome! Thanks!
