### ISSUE TITLE
Tooltips for buttons?

### ISSUE THREAD

**Issue by andybak** [lkwq007/stablediffusion-infinity#41]
Especially icon buttons. I would love to start with a vague idea of the difference between "curly arrow" and "bendy arrow"!

(side note - are there docs I've overlooked? tooltips would be better but "guessing" comes a distant third in my onboarding preferences ;-) )

**Comment by lkwq007** [comment]
Three icon buttons are commit, retry, and undo respectively. 

Thanks for the suggestions. I'll update the docs and look into how to add tooltips on gradio.

**Comment by notBradPitt** [comment]
A tooltip for the parameters would also be useful. I've kinda figured out the buttons through trial and error, but I'm still not sure what strength, steps, and guidance does.

**Comment by lkwq007** [comment]
Tooltips for buttons are added in the major update.
