### ISSUE TITLE
No module named 'fpie'

### ISSUE THREAD

**Issue by tommcg** [lkwq007/stablediffusion-infinity#50]
I've been testing the previous version of this for a few days now. I just did a git pull and an now getting a new error.

```
(sd-inf) D:\stablediffusion-infinity>python app.py
patch_match compiling failed
No module named 'fpie'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

I can't seem to get fpie to install with pip install fpie or with the -I option.

And also, I can't find any place to add the share=True either in the app.py or on the command line.

Any update on getting patch_match to work on Windows?

Thanks,
Tom

**Comment by lkwq007** [comment]
> Any update on getting patch_match to work on Windows?

You may need to do a fresh clone. I just replaced the `PyPatchMatch` with a forked version. Unfortunately, git does not support this submodule modification well, so I have to modify the `.git` files manually. In that case, git pull from an old clone may not get the latest version of `PyPatchMatch`.

`fpie` is used for Photometric Correction (https://github.com/lkwq007/stablediffusion-infinity/issues/15). Currently it does not support windows

**Comment by ZeroCool22** [comment]
> > Any update on getting patch_match to work on Windows?
> 
> You may need to do a fresh clone. I just replaced the `PyPatchMatch` with a forked version. Unfortunately, git does not support this submodule modification well, so I have to modify the `.git` files manually. In that case, git pull from an old clone may not get the latest version of `PyPatchMatch`.
> 
> `fpie` is used for Photometric Correction (#15). Currently it does not support windows

Fresh clone still giving same problem!
