### ISSUE TITLE
[Feature Request] Local GPU with Gradio

### ISSUE THREAD

**Issue by iamdroppy** [lkwq007/stablediffusion-infinity#62]
**Is your feature request related to a problem? Please describe.**
Currently we need to use Huggingface, but I would love to use my own GPU

**Describe the solution you'd like**
A way of locally using Outpainting.

**Describe alternatives you've considered**
Not applicable I believe

**Additional context**
Being held by Huggingface is not that great

Thanks for the lib! It's amazing.

**Comment by lkwq007** [comment]
Hi, this repo can be deployed locally. It's different from the one on the huggingface space.
