### ISSUE TITLE
hugging face token problems

### ISSUE THREAD

**Issue by moistpepe** [lkwq007/stablediffusion-infinity#63]
when pasting my token in the huggingface token field I get the following message: 

"There was a specific connection error when trying to load CompVis/stable-diffusion-v1-4:
<class 'requests.exceptions.HTTPError'> (Request ID: <requestId>)"

alternitavely I have seen a fix requiring the insertion of "use_auth_token=''" into the ipnyb file, 
could you tell me where and how exactly to insert that there? thanks in advance

**Comment by mingiryu** [comment]
@moistpepe You need to go to https://huggingface.co/CompVis/stable-diffusion-v1-4 and get access.

**Comment by moistpepe** [comment]
> @moistpepe You need to go to https://huggingface.co/CompVis/stable-diffusion-v1-4 and get access to the model.

that worked thanks
