### ISSUE TITLE
Legacy-install-failure installing fpie package

### ISSUE THREAD

**Issue by toonpeters** [lkwq007/stablediffusion-infinity#64]
While setting up the environment file I had some problems with the fpie package. I already updated the wheel and installed the cmake package manually. 

![image](https://user-images.githubusercontent.com/74351240/195068443-7dde4811-0218-486e-a93b-03b91852760a.png)

 - OS: Ubuntu debian 18.04.6 LTS
 - CUDA 11.4
 - Nvidia RTX A5000 and Nvidia GeForce RTX 3090
 - Browser firefox

**Comment by tommcg** [comment]
I'm waiting for more info on this error as well. I'd also like patchmatch to work!

**Comment by ZeroCool22** [comment]
I'm getting same error: https://github.com/lkwq007/stablediffusion-infinity/issues/66

Installing CMAKE: **sudo apt install cmake** will not fix it?

**Comment by lkwq007** [comment]
@toonpeters 
Hi, I am not the maintainer of `fpie`. for `fpie` installation problem, please open an issue in the original repo: https://github.com/Trinkle23897/Fast-Poisson-Image-Editing
