### ISSUE TITLE
[Bug, Crash]

### ISSUE THREAD

**Issue by w-core** [lkwq007/stablediffusion-infinity#65]
Not sure if that related to main problem, but i have this error first of all. 
![Need_help_SD_Infinity_2022-10-12 041543](https://user-images.githubusercontent.com/37899429/195240264-e710fb67-64fa-45d7-a17b-6b5a41ed4492.png)

And also have crash with very last step. Am not sure how to fix that, help pls. :C
" TypeError: hold_canvas() missing 1 required positional argument: 'canvas' "

![Need_help_SD_Infinity_2022-10-12 041542](https://user-images.githubusercontent.com/37899429/195239546-2760cc90-747c-4f64-92cb-de3363eda7d2.png)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 6
      4 for item in lst:
      5     display(item)
----> 6 display_lst=base.display()
      7 display_lst.insert(-1,widgets.HBox([control_label,commit_button,retry_button,undo_button]))
      8 display_lst.insert(-1,widgets.HBox([resize_check,step_input,guidance_input,strength_slider]))

File c:\AI\stablediffusion-infinity\canvas.py:198, in InfCanvas.display(self)
    197 def display(self):
--> 198     with hold_canvas():
    199         self.clear_background()
    200         self.draw_buffer()

File c:\Users\Root\anaconda3\envs\sd-inf\lib\contextlib.py:281, in contextmanager.<locals>.helper(*args, **kwds)
    279 @wraps(func)
    280 def helper(*args, **kwds):
--> 281     return _GeneratorContextManager(func, args, kwds)

File c:\Users\Root\anaconda3\envs\sd-inf\lib\contextlib.py:103, in _GeneratorContextManagerBase.__init__(self, func, args, kwds)
    102 def __init__(self, func, args, kwds):
--> 103     self.gen = func(*args, **kwds)
    104     self.func, self.args, self.kwds = func, args, kwds
    105     # Issue 19330: ensure context manager instances have good docstrings

TypeError: hold_canvas() missing 1 required positional argument: 'canvas'

**Comment by lkwq007** [comment]
The Jupyter notebook version is no longer supported. Please check out the latest version.
