### ISSUE TITLE
Error no file named model_index.json found in directory CompVis/stable-diffusion-v1-4.

### ISSUE THREAD

**Issue by SevenSnows** [lkwq007/stablediffusion-infinity#72]
Running SD-Infinity; the Web UI loads - great.

But when I put a valid HuggingFace token into the UI the UI box returns the message

`Error no file named model_index.json found in directory CompVis/stable-diffusion-v1-4.`

Also tried 
`huggingface-cli login` in terminal which saves token to users folder; bur regardless am stuck at the above error message. 

Is this user error or a bug?
Thanks

**Comment by lkwq007** [comment]
Have you enabled your access to model weights? 
https://huggingface.co/CompVis/stable-diffusion-v1-4

**Comment by SevenSnows** [comment]
Adding the token in the box works - so closing issue

**Comment by lkwq007** [comment]
> 1. access to weights .... I have a token from Huggingface - is that what you mean? The link you gave was where I got the token from (and models) - I am just checking you mean token?

I mean consenting user agreement on the model page. (Some users might miss this step)

> yesterday pasting the token into the webUI gave the error I posted - today.... it works immediately
> Adding the token in the box works - so closing issue

Perhaps there might be something wrong with the Huggingface website?
