### ISSUE TITLE
Is it possible to use embedding trained from textual Inversion

### ISSUE THREAD

**Issue by shengyu-meng** [lkwq007/stablediffusion-infinity#77]
It is quite common to finetune stbale diffusion model by training customized embedding via textual inversion. Are there any change to load the embedding in stablediffusion-infinity?

**Comment by lkwq007** [comment]
The embeddings from textual inversion has been supported in the major update: https://github.com/lkwq007/stablediffusion-infinity/tree/major-update

**Comment by gerasy** [comment]
> The embeddings from textual inversion has been supported in the major update: https://github.com/lkwq007/stablediffusion-infinity/tree/major-update

wow, could you please tell how to setup the model.ckpt with it in the readme please?
can we just copy model.ckpt into main folder, or is there more work involved :D
thanks

**Comment by lkwq007** [comment]
> > The embeddings from textual inversion has been supported in the major update: https://github.com/lkwq007/stablediffusion-infinity/tree/major-update
> 
> wow, could you please tell how to setup the model.ckpt with it in the readme please? can we just copy model.ckpt into main folder, or is there more work involved :D thanks

Also supported in the major-update. I will update the readme when the update is ready to merge.

**Comment by shengyu-meng** [comment]
> The embeddings from textual inversion has been supported in the major update: https://github.com/lkwq007/stablediffusion-infinity/tree/major-update

Super cool~! will test that. Thanks! :)
