### ISSUE TITLE
[Bug] App does not run on Windows

### ISSUE THREAD

**Issue by catid** [lkwq007/stablediffusion-infinity#82]
Followed Windows installation instructions, using fresh Miniconda install.  This is what I get:

(sd) C:\Users\mrcat\sources\stablediffusion-infinity>python app.py
patch_match compiling failed, will fall back to edge_pad
No module named 'fpie' so PhotometricCorrection is disabled
Traceback (most recent call last):
  File "C:\Users\mrcat\sources\stablediffusion-infinity\app.py", line 1009, in <module>
    cancel_button.click(fn=None, inputs=None, outputs=None, cancels=[proceed_event])
TypeError: Clickable.click() got an unexpected keyword argument 'cancels'

(sd) C:\Users\mrcat\sources\stablediffusion-infinity>python --version
Python 3.10.6

**Comment by lkwq007** [comment]
See https://github.com/lkwq007/stablediffusion-infinity/issues/84

The gradio needs to be updated: 
```
pip install gradio==3.6
```

Also fixed with latest commit.
