### ISSUE TITLE
[Bug] Can't load config for 'runwayml/stable-diffusion-inpainting'

### ISSUE THREAD

**Issue by P4l1ndr0m** [lkwq007/stablediffusion-infinity#87]
**Describe the bug**
Hello, I am following the installation instructions on how to run the app using the latest commit (e8828eb30b3c41f49bd1194d5c574f4228239497), have done recursive clone, all good I can see the web ui and can input my Hugging Face token

BUT after clicking on "Setup" I get the following error:

![image](https://user-images.githubusercontent.com/4301170/197320136-6205fac9-b38b-479f-91d4-bafa3bd3bc31.png)

`Can't load config for 'runwayml/stable-diffusion-inpainting'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'runwayml/stable-diffusion-inpainting' is the correct path to a directory containing a model_index.json file`

I have already approved the model's terms and condition.

**My setup: 
 - OS: Windows 10
 - Miniconda 3
 - Followed install instructions as per documentation page

Thanks for your help !

**Comment by lkwq007** [comment]
You may need to accept the license agreement to access the model weights: https://huggingface.co/runwayml/stable-diffusion-inpainting

**Comment by P4l1ndr0m** [comment]
Hello, thanks for the reply. Yes have indeed accepted the license and can download the model weights manually as shown below but I still get the same error:

![image](https://user-images.githubusercontent.com/4301170/197337674-fdab61ec-7519-4231-ae25-e474c8ef51f1.png)

**Comment by P4l1ndr0m** [comment]
Found the issue to my own problem. I updated diffusers to 0.6.0
