### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionInpaintPipelineLegacy' from 'diffusers' 

### ISSUE THREAD

**Issue by ZeroCool22** [lkwq007/stablediffusion-infinity#89]
![6666](https://user-images.githubusercontent.com/13344308/197341481-ba865ab1-559e-4bfe-8888-3b9bd0c77104.jpg)

Why always some problem with this repo? lol...

Was a pain to get it working, now after a **GIT PULL** it broke again!

**Comment by lkwq007** [comment]
You need to update diffusers to 0.6.0.

**Comment by ZeroCool22** [comment]
> diffusers

Tell me the command to do it, please.

**Comment by ZeroCool22** [comment]
> 

Ok, updated it.

Now i get:

![Uploading Screenshot_7.jpg…]()

**Comment by Skiddoh** [comment]
Hello there!
i have the same error after i recently discovered and installed this repo.
Sadly the assert threw me an error even though i had version 0.6.0 installed.
To force it to version 0.6.0 nonetheless i ran "conda install diffusers=0.6.0" inside of sd-inf environment.
Giving me the following version:
![image](https://user-images.githubusercontent.com/10726090/198611244-664ea733-e7fc-4cfe-afa2-b44bc55c6fbd.png)

But it still gives me the following error message:
`Traceback (most recent call last):
  File "D:\Software\stable-diffusion-infinity\stablediffusion-infinity-master\app.py", line 11, in <module>
    assert diffusers.__version__ >= "0.6.0", "Please upgrade diffusers to 0.6.0"
AssertionError: Please upgrade diffusers to 0.6.0`

**Comment by Skiddoh** [comment]
@ZeroCool22 what ip are you using to connect to the gradio UI?

**Comment by ZeroCool22** [comment]
> @ZeroCool22 what ip are you using to connect to the gradio UI?

Thx you for reply, this was fixed the same day, i forgot to close it.
