### ISSUE TITLE
[Bug] Errors on launch

### ISSUE THREAD

**Issue by bbecausereasonss** [lkwq007/stablediffusion-infinity#90]
Followed instructions for windows.

(sd-inf) C:\Users\chlyw\Desktop\Infinity>python app.py
patch_match compiling failed, will fall back to edge_pad
No module named 'fpie' so PhotometricCorrection is disabled
Running on local URL:  http://127.0.0.1:7860

**Comment by bbecausereasonss** [comment]
Now /w outpaint get this error.

type str doesn't define __round__ method

**Comment by bbecausereasonss** [comment]
Re Docker tutorial.

WIN10:/mnt/c/users/xxx/desktop/infinity/docker$ ./docker-run.sh
./docker-run.sh: line 2: $'\r': command not found
./docker-run.sh: line 3: cd: $'.\r': No such file or directory
./docker-run.sh: line 4: $'\r': command not found
./docker-run.sh: line 26: syntax error: unexpected end of file

**Comment by bbecausereasonss** [comment]
Nothing but errors for me.

**Comment by lkwq007** [comment]
> Now /w outpaint get this error.
> 
> type str doesn't define **round** method

I don't use `round` in my code. 

> Re Docker tutorial.

git clone inside wsl2 and then run docker-run.sh

**Comment by bbecausereasonss** [comment]
Hmm, thanks. Trying to run it though Docker.

WSL2/Ubuntu + Docker. Then Git cloned, then when running 

Got this error > Unable to find image 'nvidia/cuda:11.4.2-base-ubuntu20.04' locally

Attaching to stablediffusion-infinity-sd-infinity-1
stablediffusion-infinity-sd-infinity-1  | + set -x
stablediffusion-infinity-sd-infinity-1  | + git submodule update --init --recursive
stablediffusion-infinity-sd-infinity-1  | error: could not lock config file /app/.git/modules/PyPatchMatch/config: Permission denied
stablediffusion-infinity-sd-infinity-1  | fatal: could not set 'core.worktree' to '../../../PyPatchMatch'
stablediffusion-infinity-sd-infinity-1 exited with code 1

**Comment by bbecausereasonss** [comment]
Tried to change ownership of the dir, tried to export and move WSL/Ubuntu to a diff drive. Still same error :/
https://blog.iany.me/2020/06/move-wsl-to-another-drive/

Attaching to stablediffusion-infinity-sd-infinity-1
stablediffusion-infinity-sd-infinity-1  | + set -x
stablediffusion-infinity-sd-infinity-1  | + git submodule update --init --recursive
stablediffusion-infinity-sd-infinity-1  | error: could not lock config file /app/.git/modules/PyPatchMatch/config: Permission denied
stablediffusion-infinity-sd-infinity-1  | fatal: could not set 'core.worktree' to '../../../PyPatchMatch'
stablediffusion-infinity-sd-infinity-1 exited with code 1
root@FRWRD-PC-WIN10:~/github/stablediffusion-infinity/docker#

**Comment by bbecausereasonss** [comment]
Fixed by completely uninstalling/re-installing all virtual windows components, then WSL/WSL2 + Ubuntu. Now it's fine.
