### ISSUE TITLE
[Bug] Unable to load a Local Model

### ISSUE THREAD

**Issue by Arron17** [lkwq007/stablediffusion-infinity#97]
**Describe the bug**
Unable to load any local models

**To Reproduce**
Click "Click to Setup" in the WebUI with a Custom Model Path set

**Expected behavior**
For the app to be setup for use with a Local Model

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser Microsoft Edge

**Additional context**
Tried multiple different models, SD 1.4, SD 1.5, WD 1.3 and all produce the same error.

`Using local_model: D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\wd-v1-3.ckpt
Using [runwayml/stable-diffusion-inpainting] D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\wd-v1-3.ckpt
Converting & Loading D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\wd-v1-3.ckpt
Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).`

`Using local_model: D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\SD-v1-4.ckpt
Using [runwayml/stable-diffusion-inpainting] D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\SD-v1-4.ckpt
Converting & Loading D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\SD-v1-4.ckpt
Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).`

`Using local_model: D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\v1-5-pruned-emaonly.ckpt
Using [runwayml/stable-diffusion-inpainting] D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\v1-5-pruned-emaonly.ckpt
Converting & Loading D:\Code\Stable-Diffusion\stablediffusion-infinity\checkpoints\v1-5-pruned-emaonly.ckpt
Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 9, 3, 3]).`

**Comment by bbecausereasonss** [comment]
I cannot for the life of me figure out how to even upload local models or if it's possible to create a link to them from system to docker/wsl/ubuntu :/

**Comment by lkwq007** [comment]
> Loading local model
> **Note that when loading a local checkpoint, you have to specify the correct model choice before setup.**

The mentioned checkpoints are not `stablediffusion-inpainting` model

**Comment by lkwq007** [comment]
> I cannot for the life of me figure out how to even upload local models or if it's possible to create a link to them from system to docker/wsl/ubuntu :/

For example, if the path to your checkpoint is `C:\Users\username\checkpoint`

In wsl, the corresponding path is `/mnt/c/Users/username/checkpoint`

**Comment by Gonoshift** [comment]
> > I cannot for the life of me figure out how to even upload local models or if it's possible to create a link to them from system to docker/wsl/ubuntu :/
> 
> For example, if the path to your checkpoint is `C:\Users\username\checkpoint`
> 
> In wsl, the corresponding path is `/mnt/c/Users/username/checkpoint`

I've set the WSL corresponding path of my model, but it seems to always load the hardcoded runwayml/stable-diffusion model, what am I doing wrong? 
I'm not providing a huggingface token since it says that its not required for local models.

### Settings:
![image](https://user-images.githubusercontent.com/12871341/197504749-b27bf9c8-11c3-4747-b8ec-2f560c3a0bbb.png)

### Result:
![image](https://user-images.githubusercontent.com/12871341/197504849-e0f97339-dda5-4b39-a07e-3d0453c9c49f.png)

The log says:
```
Note that stablediffusion-inpainting+img2img-v1.5 only support remote model and requires larger vRAM
Loading runwayml/stable-diffusion-v1-5
runwayml/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.
```
