### ISSUE TITLE
[Bug] Processing times incredibly slow.

### ISSUE THREAD

**Issue by bbecausereasonss** [lkwq007/stablediffusion-infinity#98]
Forgive me for my noobness, but the processing time for inpaint is insanely slow compared to anything else I've ever done on my 4090. Just trying to figure out why and what can be done if anything? I'm using Docker/WSL2/Ubuntu

Also, noticing that a lot of the time IMG2IMG and other options simply do not work.

https://www.dropbox.com/s/8v8a2jlalxcwbtm/IMG2IMG_Issue.mp4?dl=0

Also seeing this a lot 

ValueError: axes don't match array

**Comment by lkwq007** [comment]
1. you don't even tell me the steps to reproduce your errors
2. img2img only works for certain model types and only works for the regions without missing contents
3. the performance issue is related to diffusers implementation, it has nothing to do with this program

**Comment by bbecausereasonss** [comment]
Thanks, and sorry for not being more specific. It would be great to have the details of which models don't work or even a brief description on what these models/algo's do.

**Comment by lkwq007** [comment]
> Thanks, and sorry for not being more specific. It would be great to have the details of which models don't work or even a brief description on what these models/algo's do.

check out Modelsection in the usage

https://github.com/lkwq007/stablediffusion-infinity/blob/master/docs/usage.md

> the performance issue is related to diffusers implementation, it has nothing to do with this program

It seems that this claim is incorrect. I just reproduced the performance issue and updated the code. 
Now it should work well for selection size smaller than or equal to 512x512. 
However, the major performance problem is still from the upstream or the device limitation (image size larger than 512x512 will be much slower)
